/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import data.RadioStation;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @author erick
 */
public class MainFrame extends javax.swing.JFrame {

    private RadioStation station;
    /**
     * Creates new form MainFram
     */
    public MainFrame() {
        initComponents();
        this.station = new RadioStation();
    }

    public MainFrame(RadioStation station) {
        initComponents();
        this.station = station;
        this.radioStationNameLabel.setText(station.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioStationNameLabel = new javax.swing.JLabel();
        broadcastersButton = new javax.swing.JButton();
        showsButton = new javax.swing.JButton();
        songsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioStationNameLabel.setText("jLabel1");

        broadcastersButton.setText("Administrar Locutores");
        broadcastersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broadcastersButtonActionPerformed(evt);
            }
        });

        showsButton.setText("Administrar Programas");
        showsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showsButtonActionPerformed(evt);
            }
        });

        songsButton.setText("Administrar Canciones");
        songsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songsButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(radioStationNameLabel)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(songsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(broadcastersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(radioStationNameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(broadcastersButton)
                    .addComponent(showsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songsButton)
                    .addComponent(exitButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void broadcastersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broadcastersButtonActionPerformed
        BroadcastersFrame frame = new BroadcastersFrame(this.station.getBroadcasters(), this);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_broadcastersButtonActionPerformed

    private void showsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showsButtonActionPerformed
        ShowsFrame frame = new ShowsFrame(this.station, this);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_showsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void songsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songsButtonActionPerformed
        SongsFrame frame = new SongsFrame(this.station.getSongs(), this);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_songsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton broadcastersButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel radioStationNameLabel;
    private javax.swing.JButton showsButton;
    private javax.swing.JButton songsButton;
    // End of variables declaration//GEN-END:variables

}
